name: build-vcenter

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - src/**
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      id: version
      run: |
        ./build.sh

    - name: Get Version
      id: version
      run: |
        IMAGE_VERSION=$(cat version.txt)
        echo "::set-output name=IMAGE_VERSION::${IMAGE_VERSION}"     

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./vcenter
        file: ./vcenter/Dockerfile
        push: true
        tags: | 
          ${{ secrets.DOCKER_HUB_USERNAME }}/shortpaste:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/shortpaste:${{ steps.version.outputs.IMAGE_VERSION }}